language: node_js

node_js: 8

branches:
  only:
  - master

cache:
  directories:
  - node_modules

deploy:
  provider: npm
  email: vdsabev@gmail.com
  api_key:
    secure: Ogx7ppN43ADL9Hhtw2xueo6VragLF12zEugqASmN9zAmGtsUUY23Vaf9vmUnnpJAD/wwsoaoGL42Z0Dk9VA9fJzKzrCDAlBQ8556Go/4qkRH6iDET7OnLaOeLifw20lDCJ+FVmF5XKPZomWJ1Lmy6tEN+PHLFiZjjKTKKa8nPr30crsrKg1AufXkyRsABqDwZ6luNPmWeZYh+918URAabNzA8RJvQElHPzUJ8zVBXteof0LgGxGwq9veWrEDD7dK6jrfDC8QqHOszONQUcIqmLEV9VAdLMAUHEDE003apTzvFTQcEXRkMFECjdkILCrEQ/uWWiR2a4BAdBzPg9AV0HgdCVF2xGtG+3vNav2dfzYUIP7RTY1Ixyw6gsvlE5QGgbJICwbEGAxLHzyLYFYy1CQmytZt8XLSFd/J7QKp5KRxCYpWxjt4q1oUckTpORJQEtgDnxjPML7+N5ud4MzdmfPxXt5PQVVg3ZnC9DUq3gWxEOTqvzW3yzDig5UDEB1MimNTWZIMvQwdNzJbRUEJbyu9tmTUt9+x+VFdMUWIHEPQfmrQB18Hncc9LirqyfzMUnWoBRUjaBeGOAp1JwqS0BOEXhMhcTZMkCrHP2JbxrrJtW6xlsAMzCFG01yL+g159/1yrQp2vjJ6BiNnWv4yKQI+WSQJjhtpPTiTda67SAM=
  on:
    repo: vdsabev/sneer
  skip_cleanup: true
